version: '3.8'
services:
  db:
    image: postgres:15
    container_name: jmc_client_manager
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo2025
      POSTGRES_DB: jmc_clients_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: