export const AUTH_REPOSITORY_TOKEN = 'AUTH_REPOSITORY_TOKEN';

export const CLIENT_REPOSITORY_TOKEN = 'CLIENT_REPOSITORY_TOKEN';

export const CLIENT_STATUS_REPOSITORY_TOKEN = 'CLIENT_STATUS_REPOSITORY_TOKEN';
